package com.bidradar.bid.infra.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public record G2bNoticeItem(
        String bidNtceNo,
        String bidNtceOrd,
        String bidNtceNm,
        String ntceInsttNm,
        String bidMethdNm,
        String cntrctCnclsMthdNm,
        String bdgtAmt,
        String cnstrtsiteRgnNm,
        String bidNtceDt,
        String bidQlfctRgstDt,
        String bidClseDt,
        String opengDt,
        String bidNtceDtlUrl,
        String indstrytyLmtYn,
        String ntceKindNm,
        String rgstDt,
        String ntceSpecDocUrl1,
        String ntceSpecDocUrl2,
        String ntceSpecDocUrl3,
        String ntceSpecDocUrl4,
        String ntceSpecDocUrl5,
        String ntceSpecDocUrl6,
        String ntceSpecDocUrl7,
        String ntceSpecDocUrl8,
        String ntceSpecDocUrl9,
        String ntceSpecDocUrl10,
        String ntceSpecFileNm1,
        String ntceSpecFileNm2,
        String ntceSpecFileNm3,
        String ntceSpecFileNm4,
        String ntceSpecFileNm5,
        String ntceSpecFileNm6,
        String ntceSpecFileNm7,
        String ntceSpecFileNm8,
        String ntceSpecFileNm9,
        String ntceSpecFileNm10,
        String mainCnsttyNm,
        String pubPrcrmntClsfcNm,
        String dtilPrdctClsfcNoNm
) {}
